apiVersion : apps/v1
kind: Deployment
metadata:
  name: henrydleaopipelinesjavascriptdocker 
spec:
  selector:
    matchLabels:
      app: henrydleaopipelinesjavascriptdocker
  replicas: 1
  template:
    metadata:
      labels:
        app: henrydleaopipelinesjavascriptdocker 
    spec:
      containers:
        - name: henrydleaopipelinesjavascriptdocker 
          image: meutestehenry.azurecr.io/henrydleaopipelinesjavascriptdocker
          ports:
          - containerPort: 8080
