apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: henrydleaopipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: henrydleaopipelinesjavascriptdocker 
    spec:
      containers:
        - name: henrydleaopipelinesjavascriptdocker 
          image: meutestehenry.azurecr.io/henrydleaopipelinesjavascriptdocker
          ports:
          - containerPort: 8080